### PR TITLE
Notebooks read files that start with xyz

### PR DESCRIPTION
**Pull request by kjohnston73**

### CODE REVIEW

**Review by kyle-woodward — CHANGES_REQUESTED** [review]
2 'Gotchas' - the second of which may require more thought:
1. at present, if you have more than one file in your workspace meeting the conditions set up in `utils.og_file_input()`, the function will return the first occurrence, which - due to our date_id suffixes in the filenames - in every case will return the *oldest* version of the file. This can be resolved by compiling each file meeting the condition in the for-loop into a list, and then returning the element in the list that is *newest* version of the file based on the datetime_id suffix. 
2. If no files meet the condition in the func, the func returns `None` and you will get an error that you can't `os.path.join()` a `None`. We could either write in error handling within that new function to instead print something more logical to the user when the function is going to return `None` (e.g. `f"No files meet the criteria: prefix:{prefix} filetype:{filetype} etc"`), which would, in effect make the `check_exists` func obsolete. Alternatively, you could see about building in the `check_exists` func into your new func. I'm cool with either as long as we get the right file retrieved in the end.

**Comment by kjohnston73** [comment]
I can work on those problems. There are several input datasets that do not have a date_id suffix or do not have the suffix in the yyyymmdd format... Maybe it would be good to have something that appends a standardized date_id suffix to the files at the time of download/import so that the og_file_input function can remain simple but work for all input files? Other ideas? The files with this hitch are:
accg...ipynb - suffix is yyyy only
append.ipynb - caltrans line import has a 'c' at the end of the datetime_id suffix for some reason?
caltrans.ipynb - neither input file has a date_id suffix, instead each has a 'FY2022' time stamp in the middle of the file name
nfpors....ipynb - BIA and FWS inputs, neither one has a date_id suffix
pfirs.ipynb - suffix is in format (yyyy_yyyy)
usfs....ipynb - no date_id suffix on input file

**Comment by kyle-woodward** [comment]
Aha, I see. Yes the way that Carl was using his "select" tool to download data from web services, he has that dateid suffix formatting built in. I suspect it is the datasets given to us in other forms (via email, direct downloads off a server) where we strayed from adhering to that strict yyyymmdd formatting. For now, when you're coding and testing it, you can just rename those problem files or copies of them, and assume that this will get fixed for the real production cycle. We will bring this up to @crudeen to keep in mind going forward.

**Comment by kjohnston73** [comment]
Copy that. I'm thinking of sorting the list of file names with prefix ____ by suffix then returning the last file in that list (the one with the most recent date). Can you think of any cases where that wouldn't work?

**Comment by kjohnston73** [comment]
I have a function that is working, utilizes the date_id suffix to find the most recent file, and throws an error if the file does not exist. I pushed it into my working branch, not sure if I have to pull request again if that auto updates? There are only 2 catches.

1) The caltrans data won't "work" with my function currently because in the gdb we have "Vegetation_Control_FY2022_Statewide_Point_Activities" and "Vegetation_Control_FY2022_Statewide_Point_Treatments". The workflow has been using the "..._Activities" datasets but because my function sorts the files alpha-numerically based on the date_id suffix, the function grabs the "..._Treatments" data. I have not seen anywhere in the workflow that we use the "..._Treatments" data, so perhaps just deleting it from the gdb will fix this hitch.

2) My function throws an error but the code block still runs and throws the "can't join with 'NoneType' error for the next line. I'm not sure how to make my error show up in the red box and have the code block stop running. See the screenshot below. 
image

**Comment by kyle-woodward** [comment]
Awesome
1. For CalTrans and any other files, the general idea is that every file must have a suffix indicating its time of download/reception from stakeholders. So for those, we can either make sure to append a yyyymmdd suffix at the end of those files before running the notebook, OR if its really only going to be a FY2022, FY2023 kind of cadence for receiving new data, just put that as the suffix and it'll find the right one. Also since the Treatments and Activities part of the file do seem to indicate they are different datasets, then that part of the filename should be included in the string passed to the prefix argument.
2. To get your code to raise errors with your own custom error handling, you use `raise` not `print`. I made that change in the func() as well as making the code less complicated looking. Please test that it works as intended.

**Comment by kjohnston73** [comment]
og_file_input function tested, and had to do one more push because I found a couple leftover testing cells I forgot to delete before. Should be good to merge...

**Review by kyle-woodward — APPROVED** [review]
nice job! check_exists() was clunky anyway

**Pull request merged**
